# Copyright (c) Qualcomm Innovation Center, Inc. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause-Clear

services:
  web-ui:
    image: web-ui:latest
    platform: arm64
    container_name: web-ui
    hostname: web-ui
    user: root
    restart: always
    command: bash run.sh
    deploy:
      resources:
        reservations:
          devices:
            - driver: cdi
              device_ids:
                - qualcomm.com/device=cdi-hw-acc
    network_mode: host
  asr:
    image: asr:latest
    platform: arm64
    container_name: ASR
    hostname: ASR
    user: root
    restart: always
    command: bash run.sh
    volumes:
      - /opt/asr/:/app/Speech-To-Text/ai-engine-direct-helper/samples/python/whisper_base_en/models/
      - /usr/lib/dsp/cdsp1/libc++.so.1:/usr/lib/dsp/cdsp1/libc++.so.1
      - /usr/lib/dsp/cdsp1/libc++abi.so.1:/usr/lib/dsp/cdsp1/libc++abi.so.1
    deploy:
      resources:
        reservations:
          devices:
            - driver: cdi
              device_ids:
                - qualcomm.com/device=cdi-hw-acc
    expose:
      - 8081
    network_mode: host
  text2image:
    image: text2image:latest
    platform: arm64
    container_name: Text2Image
    hostname: Text2Image
    user: root
    restart: always
    command: bash run.sh
    volumes:
      - /opt/text2img/:/app/Image-Generation/ai-engine-direct-helper/samples/python/stable_diffusion_v1_5/models/
      - /usr/lib/dsp/cdsp1/libc++.so.1:/usr/lib/dsp/cdsp1/libc++.so.1
      - /usr/lib/dsp/cdsp1/libc++abi.so.1:/usr/lib/dsp/cdsp1/libc++abi.so.1
    deploy:
      resources:
        reservations:
          devices:
            - driver: cdi
              device_ids:
                - qualcomm.com/device=cdi-hw-acc
    expose:
      - 8082
    network_mode: host

  text2text:
    image: text2text:latest
    platform: arm64
    container_name: Text2Text
    hostname: Text2Text
    user: root
    restart: always
    command: bash run.sh
    volumes:
      - /opt/:/opt/
      - /usr/lib/dsp/cdsp1/libc++.so.1:/usr/lib/dsp/cdsp1/libc++.so.1
      - /usr/lib/dsp/cdsp1/libc++abi.so.1:/usr/lib/dsp/cdsp1/libc++abi.so.1
    deploy:
      resources:
        reservations:
          devices:
            - driver: cdi
              device_ids:
                - qualcomm.com/device=cdi-hw-acc
    expose:
      - 8088
    network_mode: host
  
  text2speech:
    image: text2speech:latest
    platform: arm64
    container_name: TTS
    hostname: TTS
    user: root
    command: bash run.sh
    restart: always
    volumes:
      - /opt/TTS_models/:/app/Text-To-Speech/models/
      - /opt/:/app/Text-To-Speech/result/ENGLISH/
      - /usr/lib/dsp/cdsp1/libc++.so.1:/usr/lib/dsp/cdsp1/libc++.so.1
      - /usr/lib/dsp/cdsp1/libc++abi.so.1:/usr/lib/dsp/cdsp1/libc++abi.so.1
    deploy:
      resources:
        reservations:
          devices:
            - driver: cdi
              device_ids:
                - qualcomm.com/device=cdi-hw-acc
    expose:
      - 8083
    network_mode: host
